version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      - spring.datasource.url=jdbc:mysql://a1498ceadb15:3306/db_user?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:latest"
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend
    environment:
      MYSQL_DATABASE: db_user
      MYSQL_USER:
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
networks:
  backend:
    driver: custom-driver-1
